version: "3.8"

services:
  app:
    build: .
    container_name: resume-analyzer
    ports:
      - "3001:3001"
    #wait until the redis service is healthy
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/node_modules
    
  worker:
    build: .
    container_name: resume-worker
    # wait until the redis service is healthy
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "config/resumeWorker.js"]

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
